# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# Pods for Flutter
  install_all_flutter_pods(flutter_application_path)
  target 'FlutterDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterDemoUITests' do
    # Pods for testing
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_post_install(installer)
  end
end